propose:
  description: >
    Propose a motion: {motion}.
    The motion should be relevant and interesting, suitable for a detailed report.
    Come with very convincing argument in favor of the motion.
  expected_output: >
    Your clear and concise proposal for the motion.
    Include a strong argument in favor of the motion.
  agent: debater
  output_file: output/propose.md

oppose:
  description: >
    You are in opposition to the motion: {motion}.
    Come with very convincing argument against the motion.
  expected_output: >
    Your clear and concise proposal against the motion.
    Include a strong argument against the motion.
  agent: debater
  output_file: output/oppose.md

    Your clear and concise proposal for the motion.
    Include a strong argument in favor of the motion.
  agent: debater
  output_file: output/propose.md

decide:
  description: >
    Review the arguments for and against the motion: {motion}.
    Decide which side has the stronger argument.
  expected_output: >
    Your clear and concise decision on the motion.
    Include a strong argument for your decision.
  agent: judge
  output_file: output/decide.md
